/**
 * ============================================================================
 *               PGVECTOR WITH POSTGRESQL & NODE.JS - MASTERCLASS
 * ============================================================================
 * 
 * Q. WHAT IS PGVECTOR?
 * ANS: pgvector is an open-source extension for PostgreSQL that adds native support
 * for vector embeddings, vector distance metrics (Cosine, Euclidean/L2, Inner Product),
 * and fast Approximate Nearest Neighbor (ANN) index types (HNSW and IVFFlat).
 * It turns standard PostgreSQL into a battle-tested Vector Database.
 * 
 * Q. WHAT ARE VECTOR EMBEDDINGS?
 * ANS: An embedding is an array of floating-point numbers (e.g. [0.024, -0.912, 0.453...])
 * generated by an AI model (OpenAI text-embedding-3, Gemini, Cohere, HuggingFace) that captures
 * the semantic meaning, concepts, and relationships of text, images, or audio.
 * Items with similar meanings are mathematically placed closer together in multi-dimensional vector space.
 * 
 * Q. WHY USE POSTGRESQL + PGVECTOR INSTEAD OF SPECIALIZED VECTOR DATABASES (Pinecone, Weaviate, Qdrant)?
 * ANS:
 * 1. Single Database Architecture: Keep users, auth, permissions, relational metadata, and embeddings together.
 * 2. ACID Transactions & Consistency: Updating a document and its embedding in a single atomic transaction.
 * 3. Unified Relational & Vector Filtering: Run queries like `WHERE tenant_id = 42 AND price < 100 ORDER BY embedding <=> $1` in ONE query.
 * 4. Cost & Operations: Avoid paying for and managing extra cloud database services.
 * 5. Battle-Tested Reliability: PostgreSQL's 30+ years of backups, replication, high-availability, and enterprise security.
 * 
 * Q. WHAT ARE THE VECTOR DISTANCE OPERATORS IN PGVECTOR?
 * ANS:
 * 1. `<=>` Cosine Distance: 1 - Cosine Similarity. Measures angle between vectors. (Default for NLP & RAG).
 * 2. `<->` Euclidean / L2 Distance: Straight-line distance. (Default for computer vision & spatial data).
 * 3. `<#>` Negative Inner Product: Dot product. (Ultra-fast for normalized vectors).
 * 4. `<+>` L1 / Taxicab / Manhattan Distance: Sum of absolute differences (pgvector 0.7+).
 * 
 * Q. WHICH INDEX SHOULD YOU USE: HNSW OR IVFFLAT?
 * ANS:
 * - HNSW (Hierarchical Navigable Small World): Builds a multi-layer graph.
 *   Provides superior query latency and high recall (>98%). Can be created on empty tables. (RECOMMENDED DEFAULT).
 * - IVFFlat (Inverted File Flat): Clusters vectors into inverted lists using K-means.
 *   Uses less RAM and builds faster, but requires re-indexing after significant inserts and has lower recall.
 * 
 * ============================================================================
 */

const { setupPgvectorExtension } = require("./concepts/1. extension-and-schema");
const { demonstrateVectorDistances } = require("./concepts/2. vector-distances");
const { demonstrateVectorIndexing } = require("./concepts/3. indexing-hnsw-ivfflat");
const { semanticSearchWithRAG } = require("./concepts/4. semantic-search-rag");
const { setupAndRunHybridSearch } = require("./concepts/5. hybrid-search");
const { pool } = require("./db/connection");

async function runPgvectorTutorial() {
  console.log("=================================================================");
  console.log("    🚀 STARTING PGVECTOR & POSTGRESQL DEEP DIVE TUTORIAL        ");
  console.log("=================================================================\n");

  try {
    // Step 1: Create Extension and Table Schemas
    await setupPgvectorExtension();

    // Step 2: Test Distance Operators (<=>, <->, <#>)
    await demonstrateVectorDistances();

    // Step 3: Create HNSW & IVFFlat Indexes and inspect query plans
    await demonstrateVectorIndexing();

    // Step 4: Run Semantic Search and RAG Prompt Pipeline
    await semanticSearchWithRAG("How to build a scalable microservice with Node.js and PostgreSQL?");

    // Step 5: Hybrid Search with Reciprocal Rank Fusion (FTS + Vectors)
    await setupAndRunHybridSearch();

    console.log("\n=================================================================");
    console.log("    ✅ ALL PGVECTOR CONCEPTS DEMONSTRATED SUCCESSFULLY!          ");
    console.log("=================================================================");
  } catch (error) {
    console.error("❌ Error running tutorial:", error.message);
    console.log("\n💡 Note: Ensure your PostgreSQL instance has pgvector installed.");
    console.log("   Docker quickstart: docker run --name pgvector-demo -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d pgvector/pgvector:pg16");
  } finally {
    await pool.end();
  }
}

if (require.main === module) {
  runPgvectorTutorial();
}

module.exports = { runPgvectorTutorial };
