// ROOT LAYOUT (app/layout.tsx)
// - Required file: every Next.js App Router project must have exactly one.
// - Wraps EVERY route in the app, so <html> and <body> must live here (and only here).
// - It renders once and persists across navigations - it does NOT re-render/remount
//   when the user moves between pages, so state inside it (e.g. the header) survives.
// - Server Component by default - can't use hooks/state/events directly here.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ClientProvider from "@/providers/query-client-provider";

// next/font self-hosts Google fonts at build time (no request to Google at runtime,
// no layout shift/FOUC). The CSS variable is applied on <body> and consumed in globals.css.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Exporting `metadata` from a layout sets the DEFAULT <title>/<meta> for every page
// under it, unless a page/layout further down the tree overrides it.
// See app/metadata-example for per-route static and dynamic metadata.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ClientProvider is a "use client" boundary (see src/providers/query-client-provider.tsx).
            We push the boundary as low as possible so the rest of the layout above/around it
            can stay a Server Component - only what truly needs client-side React Query hooks
            gets shipped as client JS. */}
        <ClientProvider>
          <header className="p-4 border-b">
            <nav className="flex gap-4">
              <Link href={"/"}>Home</Link>
              <Link href={"/products"}>Products</Link>
            </nav>
          </header>
          {/* `children` is whatever matched route segment/page is currently active */}
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
